### ISSUE TITLE
Just a bunch of colors

### ISSUE THREAD

**Issue by xc597** [oloturia/ovcam#2]
Sorry, I still can't solve this problem, there are only a bunch of colors in the picture, I don't know how to modify. Another problem is the high latency of image transmission

**Comment by xc597** [comment]
I have the image now, but the transmission speed is a little low, the delay is relatively high, there is a good solution, brother

**Comment by oloturia** [comment]
There is no solution unfortunately. The Due is just not suited for the job. If you want a better frame rate you should use a FIFO buffer or even better a pre-made board with FIFO and camera [like this one](
https://www.hotmcu.com/ov7670-al422bfifo-camera-modulev20-p-19.html).

**Comment by xc597** [comment]
How do I wire the one with fifo?



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 24, 2023 17:46 PM
To: ***@***.***&gt;;
Cc: "Small ***@***.******@***.***&gt;;
Subject: Re: [oloturia/ovcam] Just a bunch of colors (Issue #2)




 
There is no solution unfortunately. The Due is just not suited for the job. If you want a better frame rate you should use a FIFO buffer or even better a pre-made board with FIFO and camera like this one.

**Comment by oloturia** [comment]
I don't know, I've never been able to make it work.
