### ISSUE TITLE
Seeing the video

### ISSUE THREAD

**Issue by mohammadalsmadi01** [oloturia/ovcam#4]
Hello, I'm an EEE student and I was working on a project where I needed to connect the OV7670 with the Arduino DUE, I've been trying to use the codes and files you provided, I have the right connection and I downloaded your codes, but I'm a bit lost on how I will be able to see the output(the video) would you please help me with it

**Comment by oloturia** [comment]
Hello!
First of all I have to admit that this project was just a test, it's not meant to be easily usable. If you want to change something in the interface I can help you in a very limited way. The best way to get an image or a stream from an Arduino is to get a FIFO memory that acts as a buffer between the cam and the Arduino. I've never been able to use one of those FIFOs though, as the documentation I found was confusing. That lead me to write the library on my own, and it came out... not very good.

Anyway, if you still want to use my code you have to use the Python scripts showYUV422.py, saveYUV422.py and tkinterface.py. Their usage and library requirements is in the README file. The last one is a more complex interface that you can use to write directly to the registers of the cam. It yields something like 2 fps and it acts better for taking stills than streams.
